services:
    app.exception_subscriber:
        class: AppBundle\EventSubscriber\ExceptionListener
        arguments:
            - '@jms_serializer'
        tags:
            - { name: kernel.event_subscriber }

    app.normalizer.resource_validation_exception:
        class: AppBundle\Normalizer\NotFoundHttpExceptionNormalizer
        arguments:
            - { type: 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'  }
        tags:
            - { name: app.normalizer }

    app.normalizer.not_found_exception:
        class: AppBundle\Normalizer\NotFoundHttpExceptionNormalizer
        arguments:
            - { type: 'Doctrine\ORM\EntityNotFoundException'  }
        tags:
            - { name: app.normalizer }

    manager.abstract_own_entity_manager:
        class: AppBundle\EntityManager\AbstractEntityOwnManager
        arguments:
            - '@doctrine.orm.entity_manager'

    manager.article:
        class: AppBundle\EntityManager\ArticleManager
        parent:  manager.abstract_own_entity_manager